const SIGNAL_TYPES = {
  HOUR_OF_DAY: 1,
  DAY_OF_WEEK: 2,
  // WHITE_NOISE: 3,
  TEMPERATURE: 4,
  DOLLAR_PESO_RATE: 5
};

const UPDATE_INTERVALS_MS = {
  [SIGNAL_TYPES.HOUR_OF_DAY]: 1000 * 60 * 2,
  [SIGNAL_TYPES.DAY_OF_WEEK]: 1000 * 60 * 60 * 24,
  // [SIGNAL_TYPES.WHITE_NOISE]: 1000 * 1,
  [SIGNAL_TYPES.TEMPERATURE]: 1000 * 60 * 30,
  [SIGNAL_TYPES.DOLLAR_PESO_RATE]: 1000 * 60 * 10
};

module.exports = {
  SIGNAL_TYPES,
  UPDATE_INTERVALS_MS
};
